[package]
name = "dosr"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm-siv = "0.11.1"
argh = "0.1.13"
bitvec = "1.0.1"
hound = "3.5.1"
itertools = "0.14.0"
k256 = { version = "0.13.4", features = ["ecdh"] }
rustfft = "6.2.0"
