[package]
name = "dosr"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0.97"
bitvec = "1.0.1"
clap = { version = "4.5.31", features = ["derive"] }
hound = "3.5.1"
itertools = "0.14.0"
k256 = { version = "0.13.4", features = ["ecdh"] }
rustfft = "6.2.0"
